name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # Changed to write for deploying directly to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4
          
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable  # Use this more modern action instead
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build Rust WASM package
        run: |
          cd quoridor-wasm
          wasm-pack build --target web

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: 'lts/*'  # Use LTS version instead of specific version
          cache: 'npm'
          cache-dependency-path: 'web-ui/package-lock.json'

      - name: Install dependencies
        run: |
          cd web-ui
          npm install

      - name: Prepare WASM for build
        run: |
          mkdir -p web-ui/node_modules/@wasm
          cp -r quoridor-wasm/pkg/* web-ui/node_modules/@wasm/
          
      - name: Build React app
        run: |
          cd web-ui
          npm run build
          touch dist/.nojekyll

      # Use deploy-pages alternative approach
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web-ui/dist
          branch: gh-pages
          clean: true