name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Set permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build Rust WASM package
        run: |
          cd quoridor-wasm
          wasm-pack build --target web

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'
          cache: 'npm'
          cache-dependency-path: 'web-ui/package-lock.json'

      - name: Install dependencies
        run: |
          cd web-ui
          npm install

      - name: Prepare WASM for build
        run: |
          mkdir -p web-ui/node_modules/@wasm
          cp -r quoridor-wasm/pkg/* web-ui/node_modules/@wasm/
          
      - name: Build React app
        run: |
          cd web-ui
          npm run build
          # Ensure .nojekyll exists in the dist directory
          touch dist/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      # Add this step to explicitly include upload-artifact before using upload-pages-artifact
      - name: Setup upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dummy-artifact
          path: ./web-ui/dist/index.html
          retention-days: 1
          if-no-files-found: warn
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './web-ui/dist'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2